T1S-YNQ,T1S-YNA,T1S-SQ,T1S-SA,T1S-YNA_LLM,T1S-YN_LLM_R,T1S-SA_LLM,T1S-S_LLM_R,T1S-YNA_CFG,T1S-YN_CFG_R,T1S-SA_CFG,T1S-S_CFG_R,T1S-YNA_Query,T1S-YN_Query_R,T1S-SA_Query,T1S-S_Query_R,T1S-YNA_MT,T1S-YN_MT_R,T1S-SA_MT,T1S-S_MT_R,T1S-YNA_COVE,T1S-YN_COVE_R,T1S-SA_COVE,T1S-S_COVE_R,T1S-YNA_CIMBUR,T1S-YN_CIMBUR_R,T1S-SA_CIMBUR,T1S-S_CIMBUR_R
Does Elasticsearch require the UseG1GC option to be present during its startup stage in issue 18151?,Yes,Summarize the differences observed in the execution of the test case across different versions of OpenJ9 on Linux in issue 18608,"In jdk_linux_11_openj9, there are WARNING messages reported, while in jdk_linux_17_openj9, an uncaught exception occurs. However, in jdk_linux_8_openj9, there are no reported issues or warnings.","No, the UseG1GC option is not required during Elasticsearch's startup stage in issue 18151.",0,"The test case in issue 18608 has execution problems across different versions of OpenJ9 on Linux. The affected versions include openjdk version ""1.8.0_382"" and IBM Semeru Runtime Open Edition (build...).",0.0,"No, the UseG1GC option is not required during Elasticsearch's startup stage in issue 18151.",0,"The test case in issue 18608 has execution problems across different versions of OpenJ9 on Linux, specifically versions 1.8.0_382 and 1.8.0_382. The simplified class file can be found in the attachment.",0.0,"Yes, the UseG1GC option is essential for running Elasticsearch with Semeru runtimes, as mentioned in issue 18151.",1,There are no variations in test case execution across different OpenJ9 versions on Linux in issue 18608.,0.0,"Yes, the UseG1GC option must be included during Elasticsearch's startup stage for issue 18151.",1,The affected versions are OpenJDK 1.8.0_382 and IBM Semeru Runtime Open Edition.,0.0,"No, the UseG1GC option is not required during Elasticsearch's startup stage in issue 18151.",0,The test case in issue 18608 has execution problems on OpenJ9 versions 1.8.0_382 and above on Linux.,0.0,"Yes, the UseG1GC is required during Elasticsearch startup for issue 18151.",1,The affected versions are OpenJDK 1.8.0_382 and IBM Semeru Runtime Open Edition.,0.0
does issue 17288 report a intermittent failure?,No,Summarize the reproduction steps the exception of issue 17005,Run using openj9 and with vm args '-Xgcpolicy:balanced',"Yes, the issue 17288 does report an intermittent failure.",0,"The reproduction steps for the exception of issue 17005 are to run the command ""Java -version"" and observe the output. The issue creator, xiangtianyu, tried several versions and encountered the same problem. The versions used were openjdk version ""17.0.4.1-ea"" 2022-08-12 and IBM Semeru Runtime Open Edition 17.0.4.1 (build 17.0.4.1-ea+1) with Eclipse OpenJ9 VM 17.0.4.1 (build openj9-0.33.1, JRE 17 Mac OS X aarch64-64-Bit...).",0.0,"No, issue 17288 does not report an intermittent failure.",1,"The reproduction steps for the exception in issue 17005 are as follows: 
1. Run the command ""Java -version"" in the terminal.
2. Observe the output and note the version of openjdk being used.
3. Try multiple versions of openjdk and observe that the same problem occurs.
4. Look at the stack trace in the body of the issue for more information.",0.0,"Yes, issue 17288 mentions an intermittent failure.",0,"The reproduction steps mentioned in the body of issue 17005 are: ""Java -version output"", ""I tried several versions and have the same problem.""",0.0,"No, issue 17288 is not reporting an intermittent failure.",1,"The reproduction steps for the exception of issue 17005 are to run the command ""Java -version"" and observe the output. The issue creator, xiangtianyu, tried several versions and encountered the same problem. The versions used were openjdk version ""17.0.4.1-ea"" 2022-08-12 and IBM Semeru Runtime Open Edition 17.0.4.1 (build 17.0.4.1-ea+1) with Eclipse OpenJ9 VM 17.0.4.1 (build openj9-0.33.1, JRE 17 Mac OS X aarch64-64-Bit...).",0.0,"No, issue 17288 does not report an intermittent failure.",1,,0.0,"No, issue 17288 is an intermittent failure",1,"The reproduction steps mentioned in the body of issue 17005 are to run the command ""Java -version"" and observe the output.",0.0
Does the issue 18336 happen with Adoptium builds?,No,Summarize the failure of issue 18001,"Involved a test failure in the jdk_security3_1 suite, specifically in the sun/security/ssl/SSLSocketImpl/ClientModeClientAuth.java test case. The failure occurred due to a java.lang.IllegalAccessError caused by an attempt to invoke a non-public method contains on a HashSet. This issue was encountered during a test run on Java version 17.0.9-beta with Eclipse OpenJ9 VM on macOS aarch64 platform. The failure was not successfully reproduced in subsequent test runs.","No, the issue 18336 does not happen with Adoptium builds.",1,"The issue 18001 failed due to an IllegalAccessError in the java/util/HashSet class when running the ClientModeClientAuth test in the SSLSocketImpl class. This failure occurred in an internal build of the IBM Semeru Runtime Certified Edition 17.0.9+3-202308191433 on October 17, 2023.",0.0,"No, the issue 18336 does not happen with Adoptium builds.",1,"The failure of issue 18001 is related to a failure link from an internal build, specifically from a build for the macaarch64rt2 platform. The build used Java version 17.0.9-beta and IBM Semeru Runtime Certified Edition 17.0.9+3-202308191433.",0.0,"No, issue 18336 does not occur with Adoptium builds.",1,"Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_aarch64_mac/77/)(`macaarch64rt2`):
```
java version ""17.0.9-beta"" 2023-10-17
IBM Semeru Runtime Certified Edition 17.0.9+3-202308191433 (build...",0.0,"No, the issue 18336 does not happen with Adoptium builds.",1,The issue 18001 failed due to an IllegalAccessError in the sun/security/ssl/SSLSocketImpl/ClientModeClientAuth.java file when running the jdk_security3_1 test suite. This failure occurred in an internal build of the IBM Semeru Runtime Certified Edition 17.0.9+3-202308191433 on a Mac aarch64 machine.,1.0,"Yes, there are known issues with Adoptium builds. Some examples include ""Adoptium build fails on macOS Big Sur"" and ""Adoptium build fails on Windows with Visual Studio 2019"". The issue is titled ""Recent builds of packaged Eclipse fail to launch with Semeru but succeed with Adoptium on macOS ARM"" and the body of the issue includes information about the Java version output for both Semeru and Adoptium builds.",0,The issue 18001 failed due to an IllegalAccessError in the java/util/HashSet class when running the ClientModeClientAuth test in the jdk_security3_1 test suite. This failure occurred in an internal build of OpenJDK 17 on a Mac aarch64 machine.,1.0,"No, issue 18336 is not present in Adoptium builds.",1,"Title: jdk_security3_1_FAILED sun/security/ssl/SSLSocketImpl/ClientModeClientAuth.java java.lang.IllegalAccessError: invokeinterface of non-public method 'contains(Ljava/lang/Object;)Z' in java/util/HashSet
Exceptions: java.lang.IllegalAccessError: invokeinterface of non-public method 'contains(Ljava/lang/Object;)Z' in java/util/HashSet
Body: Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_aarch64_mac/77/)(`macaarch64rt2`):
```
java version ""17.0.9-beta"" 2023-10-17
IBM Semeru Runtime Certified Edition 17.0.9+3-202308191433 (build...
Labels: test failure",1.0
is issue 17444 a blocker?,yes,Summarize the steps taken to reproduce issue 17307,enable GetStackTraceNotSuspendedStress ,"No, issue 17444 is not a blocker.",0,The steps taken to reproduce issue 17307 are to enable the `GetStackTraceNotSuspendedStress` feature and observe the error that occurs when using a VirtualThread instance whose fields are garbage collected while in use.,0.0,"No, issue 17444 is not a blocker.",0,The steps taken to reproduce issue 17307 are to enable the `GetStackTraceNotSuspendedStress` feature and observe the error that occurs when using a VirtualThread instance that has its fields garbage collected while in use.,0.0,"No, issue 17444 is not classified as a blocker.",0,"The reproduction steps outlined in issue 17307 are to enable the `GetStackTraceNotSuspendedStress` while running the `GetStackTraceNotSuspendedStressTest.java` test, which results in an error due to the GC'ing of fields in a VirtualThread instance while it is being used.",0.0,"No, issue 17444 is not considered a blocker as it is in a closed state.",0,The steps taken to reproduce issue 17307 are to enable the `GetStackTraceNotSuspendedStress` feature and observe an error where fields in a VirtualThread instance are garbage collected while it is being used. This error can be recreated by enabling the feature and observing the error in the `GetStackTraceNotSuspendedStressTest.java` file.,0.0,"No, issue 17444 is not a blocker.",0,"The steps taken to reproduce issue 17307 are to enable the `GetStackTraceNotSuspendedStress` feature and observe the error that occurs when using a VirtualThread instance whose fields are garbage collected while in use. The body of the issue titled ""VirtualThread instance fields are garbage collected while in use"" describes the issue and its potential consequences.",0.0,"No, issue 17444 is not classified as a blocker.",0,"The steps for reproducing issue 17307 are as follows: 
1. Enable the `GetStackTraceNotSuspendedStress` feature.
2. Run the `GetStackTraceNotSuspendedStressTest.java` test.
3. Observe the error where fields in a VirtualThread instance are garbage collected while it is being used.",0.0
Did the failing build in issue 18337 generate a StackOverflowError during execution? ,Yes,Summarize the error message for issue 17638,"testMillis failed due to an assertion error: ""Duration 999ms, expected >= 1000ms"".","No, the failing build in issue 18337 did not generate a StackOverflowError during execution.",0,"The error message for issue 17638 is that the test ""SleepSanity::testMillisNanos 'testMillisNanos()'"" was successful.",0.0,"Yes, the failing build in issue 18337 did generate a StackOverflowError during execution.",1,"The error message for issue 17638 is that the test ""SleepSanity::testMillisNanos 'testMillisNanos()'"" passed in jdk_lang_1.",0.0,"Yes, the failing build in issue 18337 reported a StackOverflowError during execution.",1,"OpenJDK java/lang/Thread/SleepSanity Duration 999ms, expected >= 1000ms",0.0,"Yes, the failing build in issue 18337 did produce a StackOverflowError.",1,"The error message for issue 17638 is ""04:51:09 STARTED SleepSanity::testMillisNanos 'testMillisNanos()'\r\n04:51:09 SUCCESSFUL..."".",0.0,"Yes, the failing build can be found in existing issue reports.",1,"The error message for issue 17063 is that the test ""SleepSanity::testMillisNanos 'testMillisNanos()'"" was successful.",0.0,"Yes, the build that failed in issue 18337 experienced a StackOverflowError while executing.",1,"The error message for issue 17638 is ""Duration 999ms, expected >= 1000ms"". The exception is org.opentest4j.AssertionFailedError. The relevant details include the test name, the expected and actual duration, and the line number where the error occurred. This information is consistent with the verified source and provides a summary of the key points to note from the error message, exceptions, and relevant details for issue 17638.",0.0
is 17852 a test failure?,Yes,Summarize the failures of issue 17137,"The jdk_security3_0 test case failed due to NSS initialization issues resulting in ""java.security.ProviderException"" with causes including ""sun.security.pkcs11.wrapper.PKCS11Exception"" and ""java.io.IOException"".","Yes, 17852 is a test failure.",1,"The failure of issue 17137 is summarized as ""jdk_security3_0_FAILED IOException: NSS initialization failed"".",1.0,"Yes, 17852 is a test failure.",1,The failure of issue 17137 is related to an internal build of OpenJDK 17 on Linux. The failure is caused by an ArrayIndexOutOfBoundsException in the java.lang.CharacterDataLatin1.getProperties method.,0.0,"Yes, issue 17852 is related to a test failure.",1,The failure mentioned in issue 17137 is related to an internal build of OpenJDK 17 on ppc64le Linux. The failure is caused by an ArrayIndexOutOfBoundsException in the java/lang/String/ToLowerCase method. The stack trace and relevant details can be found in the body of the issue.,0.0,"Yes, 17852 is a test failure.",1,"The failure of issue 17137 is summarized as ""jdk_security3_0_FAILED IOException: NSS initialization failed"". The failure is caused by an issue with the Eclipse OpenJ9 VM.",1.0,"Yes, 17852 is a test failure.",1,"The failure of issue 17137 is summarized as ""jdk_security3_0_FAILED IOException: NSS initialization failed"". The cause of the failure in issue 17137 is an internal build with Java version ""17.0.7"" and IBM Semeru Runtime Certified Edition 17.0.7+5. The specific part of the issue that failed is the test failure in the java/lang/String/ToLowerCase.java file. The issue numbers are 17005, 17019, 17063, 17120, and 17137. This failure can also be found in 7 other issue reports.",0.0,"Yes, issue 17852 is connected to a test failure.",1,"The failure mentioned in issue 17137 is a java.security.ProviderException with a stack trace showing the cause as a PKCS11Exception with error code 0xCE534351. This occurred during initialization of the SunPKCS11 class. This issue is consistent with existing issue reports that mention java.security.ProviderException, PKCS11Exception with error code 0xCE534351, and issues with SunPKCS11 objects in the Eclipse OpenJ9 VM.",1.0
"Was the GetThreadStateTest::testRunnable"" failure of issue 18763 "" reproduced?",No,,,"Yes, the GetThreadStateTest::testRunnable"" failure of issue 18763 was reproduced.",0,,,"Yes, the GetThreadStateTest::testRunnable"" failure of issue 18763 was reproduced.",0,,,"Yes, the failure of ""GetThreadStateTest::testRunnable"" in issue 18763 was reproduced.",0,,,"No, the GetThreadStateTest::testRunnable"" failure of issue 18763 was not successfully reproduced.",1,,,"No, the GetThreadStateTest::testRunnable failure of issue 18763 was not reproduced.",1,,,"No, the GetThreadStateTest::testRunnable failure of issue 18763 is not reproduced.",1,,
Did issue 18089 report a java.lang.RuntimeException?,Yes,,,"Yes, issue 18089 did report a java.lang.RuntimeException.",1,,,"No, the issue 18089 did not report a java.lang.RuntimeException.",0,,,"Yes, issue 18089 mentions a java.lang.RuntimeException in its description or exceptions.",1,,,"Yes, issue 18089 did report a java.lang.RuntimeException.",1,,,"Yes, there are 6 existing issue reports that mention a java.lang.RuntimeException in the body.",1,,,"Yes, issue 18089 reports a java.lang.RuntimeException",1,,
Did the failure reported in issue 18669 occur in a test environment running on a Linux system?,Yes,,,"Yes, the failure reported in issue 18669 did occur in a test environment running on a Linux system.",1,,,"Yes, the failure reported in issue 18669 did occur in a test environment running on a Linux system.",1,,,"Yes, the failure in issue 18669 happened in a test environment on a Linux system.",1,,,"Yes, the failure in issue 18669 was observed in a test environment that was using a Linux system.",1,,,,1,,,"Yes, the failure in issue 18669 did occur on a Linux system in a test environment.",1,,
Did the issue 17458 occur in JDK8?,No,,,"No, the issue 17458 did not occur in JDK8.",1,,,"Yes, the issue 17458 did occur in JDK8.",0,,,"Yes, issue 17458 is related to JDK8.",0,,,"No, the issue 17458 was not present in JDK8.",1,,,"Yes, JDK8 can be found in the list of JDK versions where issue 17458 occurred.",0,,,"No, issue 17458 is not related to JDK8",1,,
"In issue 19014, did setting the parameter -Xint prevent the exception from being thrown?",Yes,,,"No, setting the parameter -Xint did not prevent the exception from being thrown.",0,,,"No, setting the parameter -Xint did not prevent the exception from being thrown.",0,,,"No, setting the parameter -Xint did not prevent the exception from being thrown.",0,,,"No, setting the parameter -Xint did not prevent the exception from being thrown.",0,,,"
No, the exception was thrown in issue 19014.",0,,,"
No, setting the parameter -Xint did not successfully prevent the exception from being thrown.",0,,
Does OpenJ9-8  encounter any errors in issue 18608?,No,,,"No, OpenJ9-8 does not encounter any errors in issue 18608.",1,,,"Yes, OpenJ9-8 encountered an error in issue 18608. The error was reported by user TheSail28 and was closed on 2023-12-17. The error was caused by a java.lang.invoke.MethodHandles$Lookup.<init>(java.lang.Class,int) exception.",0,,,"No, there are no errors reported for OpenJ9-8 in issue 18608.",1,,,"No, OpenJ9-8 does not encounter any errors in issue 18608.",1,,,"Yes, OpenJ9-8 encountered an error in issue 18608.",0,,,"No, OpenJ9-8 does not encounter error in issue 18608.",1,,
